Added config file usage

diff --git a/pmocr-srv b/pmocr-srv
--- a/pmocr-srv
+++ b/pmocr-srv
@@ -20,74 +20,104 @@
 prog=pmocr
 progexec=pmocr.sh
 progpath=/usr/local/bin
+confdir=/etc/$prog
 pidfile=/var/run/$prog
-SCRIPT_BUILD=2016080301
+SCRIPT_BUILD=2016090601
 
-
-if [ ! -f $progpath/$progexec ] && [ ! -f $progexec ]; then
+if [ ! -f $progpath/$progexec ] && [ ! -f $progexec ]
+then
 	echo "Cannot find $prog executable in $progpath nor in local path."
 	exit 1
 fi
 
-if [ ! -w $(dirname $pidfile) ]; then
+if [ ! -w $(dirname $pidfile) ]
+then
 	pidfile=./$prog
 fi
 
 start() {
-		if [ -f $progpath/$progexec ]; then
-			$progpath/$progexec --service > /dev/null 2>&1 &
+	if [ ! -f $confdir/*.conf ]
+	then
+		echo "Cannot find any configuration files in $confdir."
+		exit 1
+	fi
+
+	errno=0
+
+	for cfgfile in $confdir/*.conf
+	do
+		if [ -f $progpath/$progexec ]
+		then
+			$progpath/$progexec $cfgfile --service > /dev/null 2>&1 &
+		elif [ -f ./$progexec ]
+		then
+			./$progexec $cfgfile --service > /dev/null 2>&1 &
 		else
 			echo "Cannot find $prog executable in $progpath"
 			exit 1
 		fi
 
 		pid=$!
-		sleep 1
-		if kill -0 $pid > /dev/null 2>&1; then
-			echo $pid > "$pidfile"
-			echo "$prog successfully started"
-			exit 0 
+		retval=$?
+
+		if [ $? == 0 ]
+		then
+			echo $pid > "$pidfile-$(basename $cfgfile)"
+			echo "$prog successfully started for configuration file $cfgfile"
 		else
-			echo "Cannot start $prog (see log file)."
-			exit 1
+			echo "Cannot start $prog for configuration file $cfgfile"
+			$errno = 1
 		fi
+	done
+
+	exit $errno
 }
 
 stop() {
-	if [ ! -f $pidfile ]; then
+	if [ ! -f $pidfile-* ]
+	then
 		echo "No running $prog instances found."
 		exit 1
 	fi
 
-	if ps -p$(cat $pidfile) > /dev/null 2>&1; then
-		kill -TERM $(cat $pidfile)
-		if [ $? == 0 ]; then
-			rm -f $pidfile
-			echo "$prog instance $(basename $pidfile) stopped."
+	for pfile in $pidfile-*
+	do
+		if ps -p$(cat $pfile) > /dev/null 2>&1
+		then
+			kill -TERM $(cat $pfile)
+			if [ $? == 0 ]
+			then
+				rm -f $pfile
+				echo "$prog instance $(basename $pfile) stopped."
+			else
+				echo "Cannot stop $prog instance $(basename $pfile)"
+			fi
 		else
-			echo "Cannot stop $prog instance $(basename $pidfile)"
+			rm -f $pfile
+			echo "$prog instance $pfile (pid $(cat $pfile)) is dead but pidfile exists."
 		fi
-	else
-		rm -f $pidfile
-		echo "$prog (pid $(cat $pidfile)) is dead."
-	fi
+	done
 }
 
 status() {
-	if [ ! -f $pidfile ]; then
+	if [ ! -f $pidfile-* ]
+	then
 		echo "Cannot find any running $prog instance."
 		exit 1
 	fi
 
 	errno=0
 
-	if ps -p$(cat $pidfile) > /dev/null 2>&1; then
-		echo "$prog instance $(basename $pidfile) is running (pid $(cat $pidfile))"
-		return 0
-	else
-		echo "$prog (pid $(cat $pidfile)) is dead."
-		errno=1
-	fi
+	for pfile in $pidfile-*
+	do
+		if ps -p$(cat $pfile) > /dev/null 2>&1
+		then
+			echo "$prog instance $(basename $pfile) is running (pid $(cat $pfile))"
+		else
+			echo "$prog instance $pfile (pid $(cat $pfile)) is dead but pidfile exists."
+			$errno=1
+		fi
+	done
 
 	exit $errno
 }
